### PR TITLE
Upgrade to python3.6

### PR DESCRIPTION
**Pull request by icywang86rui**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ChoiByungWook** [comment]
How you tested this image with the example notebooks?

**Comment by icywang86rui** [comment]
I have tested all 4 notebooks by overriding the image uri. They all passed except for the local mode one. Because we changed the behavior of local mode it's unrelated to the python version upgrade. I merged in a change to fix that - https://github.com/awslabs/amazon-sagemaker-examples/pull/696

**Comment by ChoiByungWook** [comment]
Were you able to successfully rerun the failing local mode notebook?

**Comment by icywang86rui** [comment]
yes. the notebook runs now.

**Pull request merged**
