### PR TITLE
Add Stale config

### PR DESCRIPTION
**Pull request by laurenyu**
same as https://github.com/aws/sagemaker-pytorch-container/pull/39

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by icywang86rui** [comment]
How many times does this need to be copied? Is it possible to have one copy and read it from multiple repos?

**Comment by laurenyu** [comment]
5 more times. Unfortunately, I wasn't able to find anything about reusing a template that's not just the default one in the [docs](https://github.com/probot/stale/blob/master/README.md)

**Comment by icywang86rui** [comment]
So if we need to change this one day we have to change it in 7 different repos. Can we use gitsubmodules for this?

**Comment by jesterhazy** [comment]
we are going to implement this differently. closing this PR.

**Pull request closed without merging**
